<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Maintenance extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Maintenance_model');
    } 

    /*
     * Listing of lm_maintenance
     */
    function index()
    {
        $data['lm_maintenance'] = $this->Maintenance_model->get_all_lm_maintenance();

        $this->load->view('maintenance/index',$data);
    }

    /*
     * Adding a new lm_maintenance
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('lid','Lid','required');
		$this->form_validation->set_rules('maintenance_man','Maintenance Man','required|max_length[24]');
		$this->form_validation->set_rules('check_date','Check Date','required');
		$this->form_validation->set_rules('problem','Problem','required');
		$this->form_validation->set_rules('cause','Cause','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'lid' => $this->input->post('lid'),
				'maintenance_man' => $this->input->post('maintenance_man'),
				'check_date' => $this->input->post('check_date'),
				'problem' => $this->input->post('problem'),
				'cause' => $this->input->post('cause'),
				'charge_partment' => $this->input->post('charge_partment'),
				'charge_man' => $this->input->post('charge_man'),
				'deadline' => $this->input->post('deadline'),
				'deal' => $this->input->post('deal'),
				'status' => $this->input->post('status'),
            );
            
            $lm_maintenance_id = $this->Maintenance_model->add_lm_maintenance($params);
            redirect('maintenance/index');
        }
        else
        {

			$this->load->model('Lift_model');
			$data['all_lm_lift'] = $this->Lift_model->get_all_lm_lift();
                
            $this->load->view('maintenance/add',$data);
        }
    }  

    /*
     * Editing a lm_maintenance
     */
    function edit($id)
    {   
        // check if the lm_maintenance exists before trying to edit it
        $lm_maintenance = $this->Maintenance_model->get_lm_maintenance($id);
        
        if(isset($lm_maintenance['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('lid','Lid','required');
			$this->form_validation->set_rules('maintenance_man','Maintenance Man','required|max_length[24]');
			$this->form_validation->set_rules('check_date','Check Date','required');
			$this->form_validation->set_rules('problem','Problem','required');
			$this->form_validation->set_rules('cause','Cause','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'lid' => $this->input->post('lid'),
					'maintenance_man' => $this->input->post('maintenance_man'),
					'check_date' => $this->input->post('check_date'),
					'problem' => $this->input->post('problem'),
					'cause' => $this->input->post('cause'),
					'charge_partment' => $this->input->post('charge_partment'),
					'charge_man' => $this->input->post('charge_man'),
					'deadline' => $this->input->post('deadline'),
					'deal' => $this->input->post('deal'),
					'status' => $this->input->post('status'),
                );

                $this->Maintenance_model->update_lm_maintenance($id,$params);            
                redirect('maintenance/index');
            }
            else
            {   
                $data['lm_maintenance'] = $this->Maintenance_model->get_lm_maintenance($id);
    
				$this->load->model('Lift_model');
				$data['all_lm_lift'] = $this->Lift_model->get_all_lm_lift();

                $this->load->view('maintenance/edit',$data);
            }
        }
        else
            show_error('The lm_maintenance you are trying to edit does not exist.');
    } 

    /*
     * Deleting lm_maintenance
     */
    function remove($id)
    {
        $lm_maintenance = $this->Maintenance_model->get_lm_maintenance($id);

        // check if the lm_maintenance exists before trying to delete it
        if(isset($lm_maintenance['id']))
        {
            $this->Maintenance_model->delete_lm_maintenance($id);
            redirect('maintenance/index');
        }
        else
            show_error('The lm_maintenance you are trying to delete does not exist.');
    }
    
}
