<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Overhaul extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Overhaul_model');
        $this->load->model('Elevator_model');
        $this->load->model('Escalator_model');
    } 

    /*
     * Listing of lm_overhaul
     */
    function index()
    {
        $data['overhaul'] = $this->Overhaul_model->get_all_overhaul();

        $this->load->view('overhaul/index',$data);
    }

    /*
     * Adding a new lm_overhaul
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('lid','Lid','required');
		$this->form_validation->set_rules('f_create','F Create','required');

        $escalators = $this->Escalator_model->get_all_escalator();
        $elevators = $this->Elevator_model->get_all_elevator();
        $data = array('escalators'=>$escalators,'elevators'=>$elevators);
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'lid' => $this->input->post('lid'),
				'f_create' => $this->input->post('f_create'),
				'f_description' => $this->input->post('f_description'),
				'f_cause' => $this->input->post('f_cause'),
				'f_deal' => $this->input->post('f_deal'),
				'f_change' => $this->input->post('f_change'),
				'f_done' => $this->input->post('f_done'),
				'supportor' => $this->input->post('supportor'),
				'preparer' => $this->input->post('preparer'),
				'submitor' => $this->input->post('submitor'),
				'submit_date' => date('Y-m-d H:i:s'),
            );
            
            $lm_overhaul_id = $this->Lm_overhaul_model->add_lm_overhaul($params);
            redirect('overhaul/index');
        }
        else
        {
            $this->load->view('overhaul/add',$data);
        }
    }  

    /*
     * Editing a lm_overhaul
     */
    function edit($id)
    {   
        // check if the lm_overhaul exists before trying to edit it
        $data['lm_overhaul'] = $this->Overhaul_model->get_overhaul($id);
        
        if(isset($data['overhaul']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('lid','Lid','required');
			$this->form_validation->set_rules('f_create','F Create','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'lid' => $this->input->post('lid'),
					'f_create' => $this->input->post('f_create'),
					'f_description' => $this->input->post('f_description'),
					'f_cause' => $this->input->post('f_cause'),
					'f_deal' => $this->input->post('f_deal'),
					'f_change' => $this->input->post('f_change'),
					'f_done' => $this->input->post('f_done'),
					'supportor' => $this->input->post('supportor'),
					'preparer' => $this->input->post('preparer'),
					'submitor' => $this->input->post('submitor'),
                );

                $this->Lm_overhaul_model->update_lm_overhaul($id,$params);            
                redirect('overhaul/index');
            }
            else
            {
                $this->load->view('overhaul/edit',$data);
            }
        }
        else
            show_error('The lm_overhaul you are trying to edit does not exist.');
    } 

    /*
     * Deleting lm_overhaul
     */
    function remove($id)
    {
        $overhaul = $this->Overhaul_model->get_overhaul($id);

        // check if the lm_overhaul exists before trying to delete it
        if(isset($overhaul['id']))
        {
            $this->Overhaul_model->delete_overhaul($id);
            redirect('overhaul/index');
        }
        else
            show_error('The lm_overhaul you are trying to delete does not exist.');
    }
    
}
