<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Station extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Station_model');
    } 

    /*
     * Listing of lm_station
     */
    function index()
    {
        $data['lm_station'] = $this->Station_model->get_all_lm_station();

        $this->load->view('station/index',$data);
    }

    /*
     * Adding a new lm_station
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[16]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'grade' => $this->input->post('grade'),
				'parent' => $this->input->post('parent'),
				'comments' => $this->input->post('comments'),
				'thumbnail' => $this->input->post('thumbnail'),
            );
            
            $lm_station_id = $this->Station_model->add_lm_station($params);
            redirect('station/index');
        }
        else
        {
            $this->load->view('station/add');
        }
    }  

    /*
     * Editing a lm_station
     */
    function edit($id)
    {   
        // check if the lm_station exists before trying to edit it
        $lm_station = $this->Station_model->get_lm_station($id);
        
        if(isset($lm_station['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[16]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'grade' => $this->input->post('grade'),
					'parent' => $this->input->post('parent'),
					'comments' => $this->input->post('comments'),
					'thumbnail' => $this->input->post('thumbnail'),
                );

                $this->Station_model->update_lm_station($id,$params);            
                redirect('station/index');
            }
            else
            {   
                $data['lm_station'] = $this->Station_model->get_lm_station($id);
    
                $this->load->view('station/edit',$data);
            }
        }
        else
            show_error('The lm_station you are trying to edit does not exist.');
    } 

    /*
     * Deleting lm_station
     */
    function remove($id)
    {
        $lm_station = $this->Station_model->get_lm_station($id);

        // check if the lm_station exists before trying to delete it
        if(isset($lm_station['id']))
        {
            $this->Station_model->delete_lm_station($id);
            redirect('station/index');
        }
        else
            show_error('The lm_station you are trying to delete does not exist.');
    }
    
}
