<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Admin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lm_admin by id
     */
    function get_lm_admin($id)
    {
        return $this->db->get_where('lm_admin',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all lm_admin
     */
    function get_all_lm_admin()
    {
        return $this->db->get('lm_admin')->result_array();
    }
    
    /*
     * function to add new lm_admin
     */
    function add_lm_admin($params)
    {
        $this->db->insert('lm_admin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lm_admin
     */
    function update_lm_admin($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('lm_admin',$params);
        if($response)
        {
            return "lm_admin updated successfully";
        }
        else
        {
            return "Error occuring while updating lm_admin";
        }
    }
    
    /*
     * function to delete lm_admin
     */
    function delete_lm_admin($id)
    {
        $response = $this->db->delete('lm_admin',array('id'=>$id));
        if($response)
        {
            return "lm_admin deleted successfully";
        }
        else
        {
            return "Error occuring while deleting lm_admin";
        }
    }
}
