<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Lift_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lm_lift by id
     */
    function get_lm_lift($id)
    {
        return $this->db->get_where('lm_lift',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all lm_lift
     */
    function get_all_lm_lift()
    {
        return $this->db->get('lm_lift')->result_array();
    }

    function record_count($post)
    {
        if(isset($post)){
            $this->db->select('a.*,b.name as station1,c.name as substation1');
            $this->db->from('lm_lift a');
            $this->db->join('lm_station b','a.station=b.id');
            $this->db->join('lm_station c','a.substation=c.id');
            if(isset($post['station'])){
                $this->db->where('b.id',$post['station']);
            }
            $query = $this->db->get();
            return $query->num_rows();
        }else{
            return $this->db->count_all('lm_lift');
        }
    }


    function get_all_lift()
    {
        $sql = "select a.*,b.name station1,c.name substation1 from lm_lift a, lm_station b,lm_station c where a.station=b.id and a.substation = c.id;";
        $query = $this->db->query($sql);
        return $query->result_array();
    }

    function get_lifts2($limit=15,$page=1,$post)
    {
        $start = $limit * ($page-1);
        $sql = "select a.*,b.name station1,c.name substation1 from lm_lift a, lm_station b,lm_station c where a.station=b.id and a.substation = c.id LIMIT $start,$limit";
        $query = $this->db->query($sql);
        return $query->result_array();
    }


    function get_lifts($limit=15,$page=1,$post)
    {
        $offset = ($page-1) * $limit;
        $this->db->select('a.*,b.name as station1,c.name as substation1');
        $this->db->from('lm_lift a');
        $this->db->join('lm_station b','a.station=b.id');
        $this->db->join('lm_station c','a.substation=c.id');

        if(isset($post['station'])){
            $this->db->where('b.id',$post['station']);
        }
        $this->db->limit($limit,$offset);
        $query = $this->db->get();
        return $query->result_array();
    }

    /*
     * function to add new lm_lift
     */
    function add_lm_lift($params)
    {
        $this->db->insert('lm_lift',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lm_lift
     */
    function update_lm_lift($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('lm_lift',$params);
        if($response)
        {
            return "lm_lift updated successfully";
        }
        else
        {
            return "Error occuring while updating lm_lift";
        }
    }
    
    /*
     * function to delete lm_lift
     */
    function delete_lm_lift($id)
    {
        $response = $this->db->delete('lm_lift',array('id'=>$id));
        if($response)
        {
            return "lm_lift deleted successfully";
        }
        else
        {
            return "Error occuring while deleting lm_lift";
        }
    }
}
