<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Lift_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lm_lift by id
     */
    function get_lm_lift($id)
    {
        return $this->db->get_where('lm_lift',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all lm_lift
     */
    function get_all_lm_lift()
    {
        return $this->db->get('lm_lift')->result_array();
    }
    
    /*
     * function to add new lm_lift
     */
    function add_lm_lift($params)
    {
        $this->db->insert('lm_lift',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lm_lift
     */
    function update_lm_lift($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('lm_lift',$params);
        if($response)
        {
            return "lm_lift updated successfully";
        }
        else
        {
            return "Error occuring while updating lm_lift";
        }
    }
    
    /*
     * function to delete lm_lift
     */
    function delete_lm_lift($id)
    {
        $response = $this->db->delete('lm_lift',array('id'=>$id));
        if($response)
        {
            return "lm_lift deleted successfully";
        }
        else
        {
            return "Error occuring while deleting lm_lift";
        }
    }
}
