<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Maintenance_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lm_maintenance by id
     */
    function get_lm_maintenance($id)
    {
        return $this->db->get_where('lm_maintenance',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all lm_maintenance
     */
    function get_all_lm_maintenance()
    {
        return $this->db->get('lm_maintenance')->result_array();
    }
    
    /*
     * function to add new lm_maintenance
     */
    function add_lm_maintenance($params)
    {
        $this->db->insert('lm_maintenance',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lm_maintenance
     */
    function update_lm_maintenance($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('lm_maintenance',$params);
        if($response)
        {
            return "lm_maintenance updated successfully";
        }
        else
        {
            return "Error occuring while updating lm_maintenance";
        }
    }
    
    /*
     * function to delete lm_maintenance
     */
    function delete_lm_maintenance($id)
    {
        $response = $this->db->delete('lm_maintenance',array('id'=>$id));
        if($response)
        {
            return "lm_maintenance deleted successfully";
        }
        else
        {
            return "Error occuring while deleting lm_maintenance";
        }
    }
}
