<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Overhaul_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lm_overhaul by id
     */
    function get_overhaul($id)
    {
        return $this->db->get_where('overhaul',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all lm_overhaul
     */
    function get_all_overhaul()
    {
        return $this->db->get('overhaul')->result_array();
    }
    
    /*
     * function to add new lm_overhaul
     */
    function add_overhaul($params)
    {
        $this->db->insert('overhaul',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lm_overhaul
     */
    function update_overhaul($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('overhaul',$params);
        if($response)
        {
            return "lm_overhaul updated successfully";
        }
        else
        {
            return "Error occuring while updating lm_overhaul";
        }
    }
    
    /*
     * function to delete lm_overhaul
     */
    function delete_overhaul($id)
    {
        $response = $this->db->delete('overhaul',array('id'=>$id));
        if($response)
        {
            return "lm_overhaul deleted successfully";
        }
        else
        {
            return "Error occuring while deleting lm_overhaul";
        }
    }
}
