<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Report_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function get_reports($get,$limit,$page=0)
    {
    	$this->build_fields( $get );
        $this->db->limit($limit,$page);
        $query = $this->db->get();
        return $query->result_array();
    }

    public function build_fields($fields)
    {
    	$this->db->select("admin.id admin_id,admin.name admin_name,admin.displayname admin_display,
            escalator.id escalator_id,escalator.lid escalator_lid,escalator.location escalator_location,
            elevator.id elevator_id,elevator.lid elevator_lid,elevator.location elevator_location,
            report.doc,report.id r_id,report.lid r_lid,report.submit_date,report.update_date");
    	$this->db->from('report');
        $this->db->join('escalator',"report.lid=escalator.lid",'left');
    	$this->db->join('elevator',"report.lid=elevator.lid",'left');
    	$this->db->join('admin',"report.submitor=admin.id");

    	if(!empty($fields['lid'])){
    	    $lid = $fields['lid'];
    	    $this->db->group_start();
            $this->db->where("escalator.lid",$lid);
    	    $this->db->or_where("elevator.lid",$lid);
    	    $this->db->group_end();
    	}

    	if(!empty($fields['location'])){
    	    $location = $fields['location'];
            $this->db->group_start();
            $this->db->like("escalator.location",$location);
            $this->db->or_like("elevator.location",$location);
            $this->db->group_end();
    	}

       

        $this->db->order_by('report.id','desc');

    }

    public function record_count($get)
    {
    	$this->build_fields($get);

    	$query = $this->db->get();
    	return $query->num_rows();
    }

    public function insert_report($lid,$doc)
    {
        $data = array(
            'lid' => $lid,
            'doc' => $doc,
            'submitor' => $this->admin_id,
        );

        $insert_id = $this->db->insert('report', $data);

        return $insert_id;
    }

    public function get_report($id)
    {
        return $this->db->get_where('report',array('id'=>$id))->row_array();
    }

    function delete_report($id)
    {
        $response = $this->db->delete('report',array('id'=>$id));
        if($response)
        {
            return "删除报告成功";
        }
        else
        {
            return "发生错误，删除报告失败";
        }
    }

}