<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Report_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function get_reports($get,$limit,$page=0)
    {
    	$this->build_fields( $get );
    }

    public function build_fields($fields)
    {
    	$this->db->select("admin.id admin_id,admin.name admin_name,admin.displayname admin_display,escalator.id escalator_id,escalator.lid escalator_lid,escalator.location escalator_location,report.doc report_doc,report.id report_id,report.lid report_lid,report.submitor report_submitor");
    	$this->db->from('report');
    	$this->db->join('escalator',"report.lid=escalator.lid");
    	$this->db->join('admin',"report.submitor=admin.id");

    	if(isset($fields['lid'])){
    	    $lid = $fields['lid'];
    	    $this->db->group_start();
    	    $this->db->where("escalator.lid",$lid);
    	    $this->db->group_end();
    	}

    	if(!empty($filter['location'])){
    	    $location = $fields['location'];
    	    $this->db->where("escalator.location",$location);
    	}

    }

    public function record_count($get)
    {
    	$this->build_fields($get);

    	$query = $this->db->get();
    	return $query->num_rows();
    }

}